services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bookreader
      POSTGRES_USER: bookreader
      POSTGRES_PASSWORD: bookreader123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - "C:/Users/franc/Documents/testebook:/media1/books"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bookreader
      - SPRING_DATASOURCE_USERNAME=bookreader
      - SPRING_DATASOURCE_PASSWORD=bookreader123

volumes:
  postgres_data: