spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookreader
    username: bookreader
    password: bookreader123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080